[web_servers]
web01 ansible_host=10.0.0.5

[monitoring_servers]
monitoring01 ansible_host=10.0.0.136

[managed_nodes:children]
web_servers
monitoring_servers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
